minimum_pre_commit_version: "3.2.0"
default_install_hook_types:
  - pre-commit
  - commit-msg
  - pre-push

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages:
          - commit-msg
        args:
          - --strict
          - feat
          - fix
          - docs
          - style
          - refactor
          - test
          - chore
          - ci
          - build
          - perf
          - revert

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.108.0
    hooks:
      - id: terraform_fmt
        args:
          - --args=-recursive
      - id: terraform_validate
        files: ^iac/(shared|environments/dev|environments/qa|environments/prod)/.*\.tf$
        stages:
          - pre-push
        args:
          - --tf-init-args=-backend=false
