sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.exclusions=\
**/.terraform/**,\
**/node_modules/**,\
**/*.tfstate,\
**/*.tfstate.*,\
**/.terraform.lock.hcl
iac/services/cognito/email_verification/template.html
